Parameters:
 
 EnviromentName:
  Type: String
  Default: UdacityProjectII
  Description: This is enviroment name
 
 VPCCIDR:
  Description: VPC IP range CIDR
  Type: String
  Default: 10.192.0.0/16
 
 PrivateSubnetICIDR:
  Description: IP range CIDR for first private subnet
  Type: String
  Default: 10.192.20.0/24
 
 PrivateSubnetIICIDR:
  Description: IP range CIDR for second private subnet
  Type: String
  Default: 10.192.21.0/24


# whatever you consider a changing value, put it as a parameter instead of hard-coding it into your script
Resources:
  VPC:
   Type: AWS::EC2::VPC
   Properties:
    CidrBlock: !Ref VPCCIDR
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
     - Key: name
       Value: !Ref EnviromentName
  
  PrivateSubnetI:
   Type: AWS::EC2::Subnet
   Properties:
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ 0, !GetAZs  '' ]
    MapPublicIpOnLaunch: false
    CidrBlock: !Ref PrivateSubnetICIDR
    Tags:
     - Key: name
       Value: !Ref EnviromentName
     - Key: Description
       Value: PrivateSubnetI

  PrivateSubnetII:
   Type: AWS::EC2::Subnet
   Properties:
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ 1, !GetAZs  '' ]
    MapPublicIpOnLaunch: false
    CidrBlock: !Ref PrivateSubnetIICIDR
    Tags:
     - Key: name
       Value: !Ref EnviromentName
     - Key: Description
       Value: PrivateSubnetII

