Parameters:
 
 EnviromentName:
  Type: String
  Default: UdacityProjectII
  Description: This is enviroment name
 
 EC2ImageID:
  Type: String
  Default: ami-0545062d0daec9308
  Description: Ec2 launch Image ID 

 VPCCIDR:
  Description: VPC IP range CIDR
  Type: String
  Default: 10.192.0.0/16
 
 PrivateSubnetICIDR:
  Description: IP range CIDR for first private subnet
  Type: String
  Default: 10.192.20.0/24
 
 PrivateSubnetIICIDR:
  Description: IP range CIDR for second private subnet
  Type: String
  Default: 10.192.21.0/24


# whatever you consider a changing value, put it as a parameter instead of hard-coding it into your script
Resources:
  VPC:
   Type: AWS::EC2::VPC
   Properties:
    CidrBlock: !Ref VPCCIDR
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
     - Key: name
       Value: !Ref EnviromentName
  
  PrivateSubnetI:
   Type: AWS::EC2::Subnet
   Properties:
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ 0, !GetAZs  '' ]
    MapPublicIpOnLaunch: false
    CidrBlock: !Ref PrivateSubnetICIDR
    Tags:
     - Key: name
       Value: !Ref EnviromentName
     - Key: Description
       Value: PrivateSubnetI

  PrivateSubnetII:
   Type: AWS::EC2::Subnet
   Properties:
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ 1, !GetAZs  '' ]
    MapPublicIpOnLaunch: false
    CidrBlock: !Ref PrivateSubnetIICIDR
    Tags:
     - Key: name
       Value: !Ref EnviromentName
     - Key: Description
       Value: PrivateSubnetII

  EC2SecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
    VpcId: !Ref VPC
    GroupDescription: Security Group for instances
    SecurityGroupEgress: 
     - CidrIp: 0.0.0.0/0
       IpProtocol: tcp
       ToPort: 80
       FromPort: 0
       Description: Web Access


     - CidrIp: 0.0.0.0/0
       IpProtocol: tcp
       ToPort: 22
       FromPort: 0
       Description: SSH access


    SecurityGroupIngress:
     - CidrIp: 0.0.0.0/0
       IpProtocol: tcp
       FromPort: 0
       ToPort: 80
       Description: Web Access

     - CidrIp: 0.0.0.0/0
       IpProtocol: tcp
       FromPort: 0
       ToPort: 22
       Description: SSH access
    Tags:
     - Key: name
       Value: !Ref EnviromentName
          





